version: '3.9'

services:
  web:
    container_name: front
    build:
      context: .
      dockerfile: front.Dockerfile
    ports:
      - 3000:3000
    command: bash -c "yarn install && yarn start"
    volumes:
      - ./frontend/:/app

  api:
    container_name: back
    build:
      context: .
      dockerfile: back.Dockerfile
    ports:
      - 3001:3001
    env_file:
      - ./backend/.env
    depends_on:
      postgres:
        condition: service_healthy
    command: bash -c "yarn install && yarn typeorm migration:run -d src/data-source && yarn dev"
    volumes:
      - ./backend/:/app

  postgres:
    container_name: bd
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - ./backend/.env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d db_finalização_ng']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
